# Generated by Django 4.1.1 on 2022-09-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_adminplace_hashtag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminPlacePhoto',
        ),
    ]
