# Generated by Django 4.1.1 on 2022-09-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_adminplace_author_adminplace_profile_img_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
