# Generated by Django 4.1.1 on 2022-09-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_place_hashtag_course_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminplace',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminplace',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='adminplace',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adminplace',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
