# Generated by Django 4.1.1 on 2022-09-24 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_adminplace_address_adminplace_lat_adminplace_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminplace',
            name='scrapper',
            field=models.ManyToManyField(blank=True, related_name='adminplacescrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='coursescrap',
            field=models.ManyToManyField(blank=True, related_name='coursescrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='place',
            name='placescrap',
            field=models.ManyToManyField(blank=True, related_name='placescrap', to=settings.AUTH_USER_MODEL),
        ),
    ]
