# Generated by Django 4.1.1 on 2022-09-24 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_adminplace_scrapper_course_coursescrap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='coursescrap',
            new_name='scrapper',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='placescrap',
            new_name='scrapper',
        ),
    ]
