# Generated by Django 4.1.1 on 2022-09-25 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_rename_coursescrap_course_scrapper_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminPlaceComment',
            new_name='PlaceComment',
        ),
        migrations.AddField(
            model_name='place',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='place',
            name='hashtag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hashrecommend'),
        ),
        migrations.AddField(
            model_name='place',
            name='scrap_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='placecomment',
            name='adminplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.place'),
        ),
        migrations.DeleteModel(
            name='AdminPlace',
        ),
    ]
