# Generated by Django 4.1.1 on 2022-09-25 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_adminplacecomment_placecomment_place_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placecomment',
            old_name='adminplace',
            new_name='place',
        ),
    ]
